// 'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider   from '@/app/StoreProvider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import NavBar from "@/app/components/Navbar/navbar";
import styles from '@/app/page.module.css'
import NavBar2 from "./components/Navbar2/navbar2";
import dotev from 'dotenv'

dotev.config()


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lemon Market",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const googleKey = process.env.NEXT_PUBLIC_GOOGLEPLACES

  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <StoreProvider>
            {/* <NavBar></NavBar> */}
            <NavBar2></NavBar2>
          <div className="all_pages">
            {children}
          </div>
        </StoreProvider>
      </AppRouterCacheProvider>
      
      </body>
      <script type="text/javascript" src={`https://maps.googleapis.com/maps/api/js?key=${googleKey}&libraries=places`} />
    </html>
  );
}
