// 'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider   from '@/app/StoreProvider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import NavBar from "@/app/components/Navbar/navbar";
import styles from '@/app/page.module.css'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lemon Market",
  // description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <StoreProvider>
            <NavBar></NavBar>
          <div className="all_pages">
            {children}
          </div>
        </StoreProvider>
      </AppRouterCacheProvider>
      
      </body>
    </html>
  );
}
