# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
# Backend
  DATABASE_URL: ${{ secrets.DB_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
   
#frontend
  NEXT_PUBLIC_OPENAIKEY: ${{ secrets.NEXT_PUBLIC_OPENAIKEY }}
  NEXT_PUBLIC_CLOUDINARYNAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARYNAME }}
  NEXT_PUBLIC_GOOGLEPLACES: ${{ secrets.NEXT_PUBLIC_GOOGLEPLACES }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: '18.18.2'

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cd server && npm run testwindows
    - run: cd client && npx jest
    
